/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gesa Rizky Nugraha
 */
public class Framepersegi extends javax.swing.JFrame {

    /**
     * Creates new form Framepersegi
     */
    public Framepersegi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sisi = new javax.swing.JTextField();
        keliling = new javax.swing.JTextField();
        luas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hapus = new javax.swing.JButton();
        proseskel = new javax.swing.JButton();
        prosesluas = new javax.swing.JButton();
        sisikel = new javax.swing.JButton();
        sisiluas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Kelilng dan Luas Persegi");

        jLabel2.setText("Sisi       :");

        jLabel3.setText("Keliling :");

        jLabel4.setText("Luas    :");

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        proseskel.setText("Keliling");
        proseskel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proseskelActionPerformed(evt);
            }
        });

        prosesluas.setText("Luas");
        prosesluas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesluasActionPerformed(evt);
            }
        });

        sisikel.setText("Sisi");
        sisikel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sisikelActionPerformed(evt);
            }
        });

        sisiluas.setText("Sisi");
        sisiluas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sisiluasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sisi, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(keliling)
                            .addComponent(luas))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(proseskel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sisikel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(prosesluas, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                    .addComponent(sisiluas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(sisikel)
                    .addComponent(sisiluas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keliling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(proseskel)
                    .addComponent(prosesluas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(hapus))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        sisi.setText(null);
        keliling.setText(null);
        luas.setText(null);
    }//GEN-LAST:event_hapusActionPerformed

    private void proseskelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proseskelActionPerformed
        // TODO add your handling code here:
        String teks = sisi.getText();// mengambil data dari text field sisi
        double inputan = Double.parseDouble(teks);//mengubah data dari string ke double
        double hasilkel = 4*inputan; // rumus keliling persegi
        String out = String.valueOf(hasilkel);//mengubah data hasil dari double ke string 
        keliling.setText(out);//mengeluarkan output
    }//GEN-LAST:event_proseskelActionPerformed

    private void prosesluasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesluasActionPerformed
        // TODO add your handling code here:
        String teks = sisi.getText();// mengambil data dari text field sisi
        double inputan = Double.parseDouble(teks);//mengubah data dari string ke double
        double hasilluas = inputan*inputan; // rumus Luas persegi
        String out = String.valueOf(hasilluas);//mengubah data hasil dari double ke string 
        luas.setText(out);//mengeluarkan output
    }//GEN-LAST:event_prosesluasActionPerformed

    private void sisikelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sisikelActionPerformed
        // TODO add your handling code here:
        String tekskel = keliling.getText();// mengambil data dari text field keliling
        double inputankel = Double.parseDouble(tekskel);//mengubah data dari string ke double
        double hasil = inputankel/4;// rumus mencari sisi bila diketahui keliling
        String out = String.valueOf(hasil);//mengubah data hasil dari double ke string 
        sisi.setText(out);//mengeluarkan output
    }//GEN-LAST:event_sisikelActionPerformed

    private void sisiluasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sisiluasActionPerformed
        // TODO add your handling code here:
        String teksluas = luas.getText();// mengambil data dari text field keliling
        double inputanluas = Double.parseDouble(teksluas);//mengubah data dari string ke double
        double hasil = Math.sqrt(inputanluas);// rumus mencari sisi bila diketahui keliling
        String out = String.valueOf(hasil);//mengubah data hasil dari double ke string 
        sisi.setText(out);//mengeluarkan output
    }//GEN-LAST:event_sisiluasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Framepersegi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Framepersegi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Framepersegi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Framepersegi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Framepersegi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField keliling;
    private javax.swing.JTextField luas;
    private javax.swing.JButton proseskel;
    private javax.swing.JButton prosesluas;
    private javax.swing.JTextField sisi;
    private javax.swing.JButton sisikel;
    private javax.swing.JButton sisiluas;
    // End of variables declaration//GEN-END:variables
}
